name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Aakashraj1535
          outputs: |
            assets/snake.svg?color_snake=%238A63F5&color_dots=%230D1117,%232563EB,%238A63F5,%23C9D1D9

      - name: Push snake output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
